### ISSUE TITLE
Error on using goto definition on standard library methods

### ISSUE THREAD

**Issue by jacksonludwig** [mfussenegger/nvim-jdtls#14]
This plugin has been working great, but I noticed a small issue in that calling goto definiton (e.g. ``lua vim.lsp.buf.definition()``) on a "built in" method (e.g. ``java.util.stream()``) causes an error like the following to popup:
![image](https://user-images.githubusercontent.com/42984254/97098756-0bbf8a00-1657-11eb-8725-6bca2b11c313.png)

My projects are made with maven, if it matters. 

Also I'm using all the latest neovim nightly and this plugin, and built the server 3 days ago.

Thanks for your work on this extension.

**Comment by mfussenegger** [comment]
I wasn't really able to reproduce the problem, but I opened a PR with some changes that might help https://github.com/mfussenegger/nvim-jdtls/pull/15

Could you try out that version?

If you get the same error, could you run `:lua require('jdtls').open_jdt_link(vim.fn.expand('%'))` in the buffer with the error to see if you get additional error messages?

**Comment by ludwj61** [comment]
Hmm, using that pull request shows an empty screen instead with the error/link at the bottom: 
![image](https://user-images.githubusercontent.com/42984254/97108539-a4c8c200-16a4-11eb-89fc-c1425b6611da.png)

I'm not sure what on my end is causing this; I just tested it again and with both coc and nvim-lspconfig I do not get this error.

running ``lua require('jdtls').open_jdt_link(vim.fn.expand('%'))`` gives me this error if using in the buffer with the error:
![image](https://user-images.githubusercontent.com/42984254/97108635-3a645180-16a5-11eb-9ae2-662ca927f43a.png)

**Comment by ludwj61** [comment]
Okay, not sure if this is related but I also noticed that code actions, although all of the new/extended options appear, they have no effect when selected. For example, if I select ``Generate toString()`` no method is created.

**Comment by mfussenegger** [comment]
Are there any errors or warnings in the log file? The logs are in `:lua print(vim.fn.stdpath('data'))` `lsp.log`

**Comment by ludwj61** [comment]
The file is actually empty, even after I trigger the error above. I will try with more minimal config (although I don't think i have anything enabled that would conflict) and report if anything changes

**Comment by ludwj61** [comment]
Okay, I apologize for the late followup, but I think I have found the problem.

When using lsp_config, commands are in the form ``vim.lsp.buf.<command>``, e.g. ``vim.lsp.buf.definition()``, whereas in this plugin, for example for code action, they are like ``require('jdtls').code_action()`` so the source ``vim.lsp.buf`` and ``require('jdtls')`` are not interchangeable.

Is there any way around this? Or do I need to make custom binds for java and this server?

**Comment by mfussenegger** [comment]
> When using lsp_config, commands are in the form vim.lsp.buf.<command>, e.g. vim.lsp.buf.definition(), whereas in this plugin, for example for code action, they are like require('jdtls').code_action() so the source vim.lsp.buf and require('jdtls') are not interchangeable.

`require('jdtls').code_action()` acts as a superset of `vim.lsp.buf.code_action()`, you should be able to use it also for other language servers.

> However I have not been able to figure out the original problem of goto definition causing the problems, and still see that minimal config.

Could you try running `:JdtCompile` ? If it doesn't succeed, eclipse.jdt.ls may have issues with your projects build configuration.

**Comment by ludwj61** [comment]
JdtCompile does run successfully, weirdly. Also to clarify my last post, although ``vim.lsp.buf.code_action()`` should work it was causing code actions not to work, whereas ``require('jdtls').code_action()`` made them work.

**Comment by mfussenegger** [comment]
I've had the plugin today as well that navigating to JDK sources didn't work anymore. This was after I updated to a newer eclipse.jdt.ls version and it was solved by clearing the workspace folder.

Maybe you could try that too.

**Comment by ludwj61** [comment]
Thanks, but unfortunately I am still getting those two issues even with a fresh workspace folder and build of jdtls. I'm still quite stuck on this issue.

**Comment by ludwj61** [comment]
@mfussenegger actually, I found a similar issue with lsp-config's implementation of code action. Could it be that this plugin and that are suffering from a similar problem? https://github.com/neovim/nvim-lspconfig/issues/397

**Comment by mfussenegger** [comment]
@ludwj61 the code action issue is unrelated to the goto definition problem. It's expected that you have to use  `require('jdtls').code_action()` and that `vim.lsp.buf.code_action()` doesn't work for most actions with jdtls. I may be able to change that.

Regarding the goto definition problem: Is there a open source project where that occurs so I could try to reproduce it? Or do you have some minimal reproduction? I need to be able to reproduce it locally to investigate further.

**Comment by ludwj61** [comment]
@mfussenegger For the goto-definition issue, I experience it will all projects. So even if I have a fresh maven project (I set them to language level 1.8 but I don't think that matters) with just something like ``Random r = new Random();`` and I try to go to the definition of random, I get the issues I stated earlier in the thread.

**Comment by mfussenegger** [comment]
```
So even if I have a fresh maven project (I set them to language level 1.8 but I don't think that matter)
```

It might matter, if you don't configure the runtimes then eclipse.jdt.ls may not be able to properly compile your project. See also my reply [here](https://github.com/mfussenegger/nvim-jdtls/issues/19#issuecomment-738943458)

The only other configuration that could be wrong is your `root_dir`. I've updated the readme to emphasize that it's important that the root_dir is set correctly - see https://github.com/mfussenegger/nvim-jdtls/commit/9de0f82c7a4f94b3459952725fe2e8cb4b01af7e

If you're on the latest nvim-jdtls commit, then `:JdtCompile` will now also load errors into the quickfix list, that may help find errors that you may have missed.

**Comment by mfussenegger** [comment]
Going to close this for now. There's not much I can do here without further information.
